name: Housekeeping - Branches staleness check

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  branch-stale-check:
    name: Branches staleness check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd:latest@sha256:3589c95379980cbc1f4b5bef64969864264c688c3f934c122a3633c054d5bf53
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Branches staleness check
        id: branch-stale-check
        run: kema-runner branch-stale-check
