name: Dependencies -  Bump versions

on:
  schedule:
    # Each hour
    - cron: 0 * * * *
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deps-bump:
    name: Dependencies bump
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd:latest@sha256:3589c95379980cbc1f4b5bef64969864264c688c3f934c122a3633c054d5bf53
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Dependencies bump
        id: deps-bump
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_PAT }}
          RENOVATE_ENDPOINT: https://api.github.com
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: "['kemadev/kemutil']"
          RENOVATE_PR_HOURLY_LIMIT: 10
        run: kema-runner deps-bump
