name: Go - CD

on:
  push:
    branches:
      # - main
      - next
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  go-cd:
    name: Go CD
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd:latest
      # GitHub Actions workaround, see https://docs.github.com/en/actions/reference/dockerfile-support-for-github-actions#user
      options: --user root:root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    concurrency:
      group: go-cd-${{ github.ref_name }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Go CD
        id: go-cd
        env:
          BRANCH: ${{ github.ref_name }}
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kema-runner cd
