name: PR - Title Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unlocked

permissions:
  contents: none

jobs:
  pr-title-check:
    name: PR title check
    permissions:
      contents: none
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd:latest@sha256:3589c95379980cbc1f4b5bef64969864264c688c3f934c122a3633c054d5bf53
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: PR title check
        id: pr-title-check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: kema-runner pr-title-check "${PR_TITLE}"
